Cai
StanleyRoberts/Nix-Bot pull request #26
Opened 2023-09-12 17:20 UTC by LordnistLost

2023-09-12 17:22 UTC, LordnistLost commented
Add necessary environment variables ("CAI_CHAR_TOKEN", "CAI_NIX_ID") to the env file (and potentially take out HF)

2023-09-15 16:03 UTC, StanleyRoberts requested changes

2023-09-15 16:03 UTC, StanleyRoberts commented on src/cogs/misc.py
> +from characterai import PyAsyncCAI as PyCAI  # type: ignore[import]
add this as a dependency please

2023-09-15 16:03 UTC, StanleyRoberts commented on src/cogs/misc.py
> +            chat = await client.chat.new_chat(CAI_NIX_ID)
can this fail? e.g. network error?

2023-09-17 19:55 UTC, StanleyRoberts approved these changes

2023-09-17 19:55 UTC, merged